version: '1.0'

networks:
  ollama-network:
    driver: bridge

volumes:
  weaviate_data:
  ollama:

services:
  vector-store-weaviate:
    container_name: vector-store-weaviate
    hostname: vector-store-weaviate
    image: 'semitechnologies/weaviate:1.31.1'
    networks: 
      - ollama-network
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_API_BASED_MODULES: 'true'
      CLUSTER_HOSTNAME: 'vector-store-weaviate'
  
  ollama:
    container_name: ollama_sematic_kernel_api
    hostname: ollama-semantic-kernel-api
    image: ollama/ollama:latest
    networks: 
      - ollama-network
    devices:
      - /dev/kfd
      - /dev/dri
    volumes:
      - /var/lib/docker/volumes/ollama/_data:/root/.ollama # Used this path hardcoded since, I already use ollama volume on my machine and by default it is created in docker lib path
  
  open-telemetry-collector:
    image: otel/opentelemetry-collector
    networks:
      - ollama-network
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-config.yaml:/etc/otel-collector-config.yaml

