networks:
  ollama-network:
    driver: bridge
    external: true

services:
  presentation-console:
    container_name: presentation-console
    build:
      context: .
      dockerfile: ./Presentation.Console/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: 'development'
    networks: 
      - ollama-network
    depends_on:
      - vector-store-weaviate
      - ollama
    
