/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChatViewRouteImport } from './routes/chat-view'

const ChatViewRoute = ChatViewRouteImport.update({
  id: '/chat-view',
  path: '/chat-view',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/chat-view': typeof ChatViewRoute
}
export interface FileRoutesByTo {
  '/chat-view': typeof ChatViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/chat-view': typeof ChatViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/chat-view'
  fileRoutesByTo: FileRoutesByTo
  to: '/chat-view'
  id: '__root__' | '/chat-view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChatViewRoute: typeof ChatViewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chat-view': {
      id: '/chat-view'
      path: '/chat-view'
      fullPath: '/chat-view'
      preLoaderRoute: typeof ChatViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ChatViewRoute: ChatViewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
